### ISSUE TITLE
Missed a possible guess

### ISSUE THREAD

**Issue by JShelton8** [NebuPookins/JS-Mastermind-Solver#7] opened 2022-08-12 20:41 UTC
Down, Right, Down, Right

<img width="1166" alt="Screen Shot 2022-08-12 at 2 37 01 PM" src="https://user-images.githubusercontent.com/111153741/184441848-ee03b7ac-87da-45f3-8294-e2a46acd04b9.png">

**Comment by NebuPookins** [comment] 2022-08-14 15:48
It looks like on the turn when the program suggested "Right, Down, Right, Down", you responded with 0 right color and column, and 0 right color, wrong column. If the solution was "Down, Right, Down, Right" I think you should have responded with 0 right color and column, and 4 right color, wrong column.

I'm closing this as "not a bug", but feel free to reopen if I misunderstood the issue.

**Closed by NebuPookins** 2022-08-14 15:48 UTC
